package me.ibrahimsn.lib

import java.util.*

object Countries {

    val list = listOf(
        Country("us", Locale("","us").isO3Country, "United States", 1),
        Country("af", Locale("","af").isO3Country, "Afghanistan (‫افغانستان‬‎)", 93),
        Country("al", Locale("","al").isO3Country, "Albania (Shqipëri)", 355),
        Country("dz", Locale("","dz").isO3Country, "Algeria (‫الجزائر‬‎)", 213),
        Country("as", Locale("","as").isO3Country, "American Samoa", 684),
        Country("ad", Locale("","ad").isO3Country, "Andorra", 376),
        Country("ao", Locale("","ao").isO3Country, "Angola", 244),
        Country("ai", Locale("","ai").isO3Country, "Anguilla", 264),
        Country("ag", Locale("","ag").isO3Country, "Antigua and Barbuda", 268),
        Country("ar", Locale("","ar").isO3Country, "Argentina", 54),
        Country("am", Locale("","am").isO3Country, "Armenia (Հայաստան)", 374),
        Country("aw", Locale("","aw").isO3Country, "Aruba", 297),
        Country("au", Locale("","au").isO3Country, "Australia", 61),
        Country("at", Locale("","at").isO3Country, "Austria (Österreich)", 43),
        Country("az", Locale("","az").isO3Country, "Azerbaijan (Azərbaycan)", 994),
        Country("bs", Locale("","bs").isO3Country, "Bahamas", 242),
        Country("bh", Locale("","bh").isO3Country, "Bahrain (‫البحرين‬‎)", 973),
        Country("bd", Locale("","bd").isO3Country, "Bangladesh (বাংলাদেশ)", 880),
        Country("bb", Locale("","bb").isO3Country, "Barbados", 246),
        Country("by", Locale("","by").isO3Country, "Belarus (Беларусь)", 375),
        Country("be", Locale("","be").isO3Country, "Belgium (België)", 32),
        Country("bz", Locale("","bz").isO3Country, "Belize", 501),
        Country("bj", Locale("","bj").isO3Country, "Benin (Bénin)", 229),
        Country("bm", Locale("","bm").isO3Country, "Bermuda", 441),
        Country("bt", Locale("","bt").isO3Country, "Bhutan (འབྲུག)", 975),
        Country("bo", Locale("","bo").isO3Country, "Bolivia", 591),
        Country("ba", Locale("","ba").isO3Country, "Bosnia and Herzegovina (Босна и Херцеговина)", 387),
        Country("bw", Locale("","bw").isO3Country, "Botswana", 267),
        Country("br", Locale("","br").isO3Country, "Brazil (Brasil)", 55),
        Country("io", Locale("","io").isO3Country, "British Indian Ocean Territory", 246),
        Country("vg", Locale("","vg").isO3Country, "British Virgin Islands", 284),
        Country("bn", Locale("","bn").isO3Country, "Brunei", 673),
        Country("bg", Locale("","bg").isO3Country, "Bulgaria (България)", 359),
        Country("bf", Locale("","bf").isO3Country, "Burkina Faso", 226),
        Country("bi", Locale("","bi").isO3Country, "Burundi (Uburundi)", 257),
        Country("kh", Locale("","kh").isO3Country, "Cambodia (កម្ពុជា)", 855),
        Country("cm", Locale("","cm").isO3Country, "Cameroon (Cameroun)", 237),
        Country("ca", Locale("","ca").isO3Country, "Canada", 1),
        Country("cv", Locale("","cv").isO3Country, "Cape Verde (Kabu Verdi)", 238),
        Country("bq", Locale("","bq").isO3Country, "Caribbean Netherlands", 599),
        Country("ky", Locale("","ky").isO3Country, "Cayman Islands", 345),
        Country("cf", Locale("","cf").isO3Country, "Central African Republic (République centrafricaine)", 236),
        Country("td", Locale("","td").isO3Country, "Chad (Tchad)", 235),
        Country("cl", Locale("","cl").isO3Country, "Chile", 56),
        Country("cn", Locale("","cn").isO3Country, "China (中国)", 86),
        Country("cx", Locale("","cx").isO3Country, "Christmas Island", 61),
        Country("cc", Locale("","cc").isO3Country, "Cocos (Keeling) Islands", 61),
        Country("co", Locale("","co").isO3Country, "Colombia", 57),
        Country("km", Locale("","km").isO3Country, "Comoros (‫جزر القمر‬‎)", 269),
        Country("cd", Locale("","cd").isO3Country, "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)", 243),
        Country("cg", Locale("","cg").isO3Country, "Congo (Republic) (Congo-Brazzaville)", 242),
        Country("ck", Locale("","ck").isO3Country, "Cook Islands", 682),
        Country("cr", Locale("","cr").isO3Country, "Costa Rica", 506),
        Country("ci", Locale("","ci").isO3Country, "Côte d’Ivoire", 225),
        Country("hr", Locale("","hr").isO3Country, "Croatia (Hrvatska)", 385),
        Country("cu", Locale("","cu").isO3Country, "Cuba", 53),
        Country("cw", Locale("","cw").isO3Country, "Curaçao", 599),
        Country("cy", Locale("","cy").isO3Country, "Cyprus (Κύπρος)", 357),
        Country("cz", Locale("","cz").isO3Country, "Czech Republic (Česká republika)", 420),
        Country("dk", Locale("","dk").isO3Country, "Denmark (Danmark)", 45),
        Country("dj", Locale("","dj").isO3Country, "Djibouti", 253),
        Country("dm", Locale("","dm").isO3Country, "Dominica", 767),
        Country("do", Locale("","do").isO3Country, "Dominican Republic (República Dominicana)", 1),
        Country("ec", Locale("","ec").isO3Country, "Ecuador", 593),
        Country("eg", Locale("","eg").isO3Country, "Egypt (‫مصر‬‎)", 20),
        Country("sv", Locale("","sv").isO3Country, "El Salvador", 503),
        Country("gq", Locale("","gq").isO3Country, "Equatorial Guinea (Guinea Ecuatorial)", 240),
        Country("er", Locale("","er").isO3Country, "Eritrea", 291),
        Country("ee", Locale("","ee").isO3Country, "Estonia (Eesti)", 372),
        Country("et", Locale("","et").isO3Country, "Ethiopia", 251),
        Country("fk", Locale("","fk").isO3Country, "Falkland Islands (Islas Malvinas)", 500),
        Country("fo", Locale("","fo").isO3Country, "Faroe Islands (Føroyar)", 298),
        Country("fj", Locale("","fj").isO3Country, "Fiji", 679),
        Country("fi", Locale("","fi").isO3Country, "Finland (Suomi)", 358),
        Country("fr", Locale("","fr").isO3Country, "France", 33),
        Country("gf", Locale("","gf").isO3Country, "French Guiana (Guyane française)", 594),
        Country("pf", Locale("","pf").isO3Country, "French Polynesia (Polynésie française)", 689),
        Country("ga", Locale("","ga").isO3Country, "Gabon", 241),
        Country("gm", Locale("","gm").isO3Country, "Gambia", 220),
        Country("ge", Locale("","ge").isO3Country, "Georgia (საქართველო)", 995),
        Country("de", Locale("","de").isO3Country, "Germany (Deutschland)", 49),
        Country("gh", Locale("","gh").isO3Country, "Ghana (Gaana)", 233),
        Country("gi", Locale("","gi").isO3Country, "Gibraltar", 350),
        Country("gr", Locale("","gr").isO3Country, "Greece (Ελλάδα)", 30),
        Country("gl", Locale("","gl").isO3Country, "Greenland (Kalaallit Nunaat)", 299),
        Country("gd", Locale("","gd").isO3Country, "Grenada", 473),
        Country("gp", Locale("","gp").isO3Country, "Guadeloupe", 590),
        Country("gu", Locale("","gu").isO3Country, "Guam", 671),
        Country("gt", Locale("","gt").isO3Country, "Guatemala", 502),
        Country("gg", Locale("","gg").isO3Country, "Guernsey", 44),
        Country("gn", Locale("","gn").isO3Country, "Guinea (Guinée)", 224),
        Country("gw", Locale("","gw").isO3Country, "Guinea-Bissau (Guiné Bissau)", 245),
        Country("gy", Locale("","gy").isO3Country, "Guyana", 592),
        Country("ht", Locale("","ht").isO3Country, "Haiti", 509),
        Country("hn", Locale("","hn").isO3Country, "Honduras", 504),
        Country("hk", Locale("","hk").isO3Country, "Hong Kong (香港)", 852),
        Country("hu", Locale("","hu").isO3Country, "Hungary (Magyarország)", 36),
        Country("is", Locale("","is").isO3Country, "Iceland (Ísland)", 354),
        Country("in", Locale("","in").isO3Country, "India (भारत)", 91),
        Country("id", Locale("","id").isO3Country, "Indonesia", 62),
        Country("ir", Locale("","ir").isO3Country, "Iran (‫ایران‬‎)", 98),
        Country("iq", Locale("","iq").isO3Country, "Iraq (‫العراق‬‎)", 964),
        Country("ie", Locale("","ie").isO3Country, "Ireland", 353),
        Country("im", Locale("","im").isO3Country, "Isle of Man", 44),
        Country("il", Locale("","il").isO3Country, "Israel (‫ישראל‬‎)", 972),
        Country("it", Locale("","it").isO3Country, "Italy (Italia)", 39),
        Country("jm", Locale("","jm").isO3Country, "Jamaica", 1876),
        Country("jp", Locale("","jp").isO3Country, "Japan (日本)", 81),
        Country("je", Locale("","je").isO3Country, "Jersey", 44),
        Country("jo", Locale("","jo").isO3Country, "Jordan (‫الأردن‬‎)", 962),
        Country("kz", Locale("","kz").isO3Country, "Kazakhstan (Казахстан)", 7),
        Country("ke", Locale("","ke").isO3Country, "Kenya", 254),
        Country("ki", Locale("","ki").isO3Country, "Kiribati", 686),
        Country("kw", Locale("","kw").isO3Country, "Kuwait (‫الكويت‬‎)", 965),
        Country("kg", Locale("","kg").isO3Country, "Kyrgyzstan (Кыргызстан)", 996),
        Country("la", Locale("","la").isO3Country, "Laos (ລາວ)", 856),
        Country("lv", Locale("","lv").isO3Country, "Latvia (Latvija)", 371),
        Country("lb", Locale("","lb").isO3Country, "Lebanon (‫لبنان‬‎)", 961),
        Country("ls", Locale("","ls").isO3Country, "Lesotho", 266),
        Country("lr", Locale("","lr").isO3Country, "Liberia", 231),
        Country("ly", Locale("","ly").isO3Country, "Libya (‫ليبيا‬‎)", 218),
        Country("li", Locale("","li").isO3Country, "Liechtenstein", 423),
        Country("lt", Locale("","lt").isO3Country, "Lithuania (Lietuva)", 370),
        Country("lu", Locale("","lu").isO3Country, "Luxembourg", 352),
        Country("mo", Locale("","mo").isO3Country, "Macau (澳門)", 853),
        Country("mk", Locale("","mk").isO3Country, "Macedonia (FYROM) (Македонија)", 389),
        Country("mg", Locale("","mg").isO3Country, "Madagascar (Madagasikara)", 261),
        Country("mw", Locale("","mw").isO3Country, "Malawi", 265),
        Country("my", Locale("","my").isO3Country, "Malaysia", 60),
        Country("mv", Locale("","mv").isO3Country, "Maldives", 960),
        Country("ml", Locale("","ml").isO3Country, "Mali", 223),
        Country("mt", Locale("","mt").isO3Country, "Malta", 356),
        Country("mh", Locale("","mh").isO3Country, "Marshall Islands", 692),
        Country("mq", Locale("","mq").isO3Country, "Martinique", 596),
        Country("mr", Locale("","mr").isO3Country, "Mauritania (‫موريتانيا‬‎)", 222),
        Country("mu", Locale("","mu").isO3Country, "Mauritius (Moris)", 230),
        Country("yt", Locale("","yt").isO3Country, "Mayotte", 262),
        Country("mx", Locale("","mx").isO3Country, "Mexico (México)", 52),
        Country("fm", Locale("","fm").isO3Country, "Micronesia", 691),
        Country("md", Locale("","md").isO3Country, "Moldova (Republica Moldova)", 373),
        Country("mc", Locale("","mc").isO3Country, "Monaco", 377),
        Country("mn", Locale("","mn").isO3Country, "Mongolia (Монгол)", 976),
        Country("me", Locale("","me").isO3Country, "Montenegro (Crna Gora)", 382),
        Country("ms", Locale("","ms").isO3Country, "Montserrat", 1664),
        Country("ma", Locale("","ma").isO3Country, "Morocco (‫المغرب‬‎)", 212),
        Country("mz", Locale("","mz").isO3Country, "Mozambique (Moçambique)", 258),
        Country("mm", Locale("","mm").isO3Country, "Myanmar (Burma) (မြန်မာ)", 95),
        Country("na", Locale("","na").isO3Country, "Namibia (Namibië)", 264),
        Country("nr", Locale("","nr").isO3Country, "Nauru", 674),
        Country("np", Locale("","np").isO3Country, "Nepal (नेपाल)", 977),
        Country("nl", Locale("","nl").isO3Country, "Netherlands (Nederland)", 31),
        Country("nc", Locale("","nc").isO3Country, "New Caledonia (Nouvelle-Calédonie)", 687),
        Country("nz", Locale("","nz").isO3Country, "New Zealand", 64),
        Country("ni", Locale("","ni").isO3Country, "Nicaragua", 505),
        Country("ne", Locale("","ne").isO3Country, "Niger (Nijar)", 227),
        Country("ng", Locale("","ng").isO3Country, "Nigeria", 234),
        Country("nu", Locale("","nu").isO3Country, "Niue", 683),
        Country("nf", Locale("","nf").isO3Country, "Norfolk Island", 672),
        Country("kp", Locale("","kp").isO3Country, "North Korea (조선 민주주의 인민 공화국)", 850),
        Country("mp", Locale("","mp").isO3Country, "Northern Mariana Islands", 1670),
        Country("no", Locale("","no").isO3Country, "Norway (Norge)", 47),
        Country("om", Locale("","om").isO3Country, "Oman (‫عُمان‬‎)", 968),
        Country("pk", Locale("","pk").isO3Country, "Pakistan (‫پاکستان‬‎)", 92),
        Country("pw", Locale("","pw").isO3Country, "Palau", 680),
        Country("ps", Locale("","ps").isO3Country, "Palestine (‫فلسطين‬‎)", 970),
        Country("pa", Locale("","pa").isO3Country, "Panama (Panamá)", 507),
        Country("pg", Locale("","pg").isO3Country, "Papua New Guinea", 675),
        Country("py", Locale("","py").isO3Country, "Paraguay", 595),
        Country("pe", Locale("","pe").isO3Country, "Peru (Perú)", 51),
        Country("ph", Locale("","ph").isO3Country, "Philippines", 63),
        Country("pl", Locale("","pl").isO3Country, "Poland (Polska)", 48),
        Country("pt", Locale("","pt").isO3Country, "Portugal", 351),
        Country("pr", Locale("","pr").isO3Country, "Puerto Rico", 1),
        Country("qa", Locale("","qa").isO3Country, "Qatar (‫قطر‬‎)", 974),
        Country("re", Locale("","re").isO3Country, "Réunion (La Réunion)", 262),
        Country("ro", Locale("","ro").isO3Country, "Romania (România)", 40),
        Country("ru", Locale("","ru").isO3Country, "Russia (Россия)", 7),
        Country("rw", Locale("","rw").isO3Country, "Rwanda", 250),
        Country("bl", Locale("","bl").isO3Country, "Saint Barthélemy (Saint-Barthélemy)", 590),
        Country("sh", Locale("","sh").isO3Country, "Saint Helena", 290),
        Country("kn", Locale("","kn").isO3Country, "Saint Kitts and Nevis", 1869),
        Country("lc", Locale("","lc").isO3Country, "Saint Lucia", 758),
        Country("mf", Locale("","mf").isO3Country, "Saint Martin (Saint-Martin (partie française))", 590),
        Country("pm", Locale("","pm").isO3Country, "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", 508),
        Country("vc", Locale("","vc").isO3Country, "Saint Vincent and the Grenadines", 1784),
        Country("ws", Locale("","ws").isO3Country, "Samoa", 685),
        Country("sm", Locale("","sm").isO3Country, "San Marino", 378),
        Country("st", Locale("","st").isO3Country, "São Tomé and Príncipe (São Tomé e Príncipe)", 239),
        Country("sa", Locale("","sa").isO3Country, "Saudi Arabia (‫المملكة العربية السعودية‬‎)", 966),
        Country("sn", Locale("","sn").isO3Country, "Senegal (Sénégal)", 221),
        Country("rs", Locale("","rs").isO3Country, "Serbia (Србија)", 381),
        Country("sc", Locale("","sc").isO3Country, "Seychelles", 248),
        Country("sl", Locale("","sl").isO3Country, "Sierra Leone", 232),
        Country("sg", Locale("","sg").isO3Country, "Singapore", 65),
        Country("sx", Locale("","sx").isO3Country, "Sint Maarten", 721),
        Country("sk", Locale("","sk").isO3Country, "Slovakia (Slovensko)", 421),
        Country("si", Locale("","si").isO3Country, "Slovenia (Slovenija)", 386),
        Country("sb", Locale("","sb").isO3Country, "Solomon Islands", 677),
        Country("so", Locale("","so").isO3Country, "Somalia (Soomaaliya)", 252),
        Country("za", Locale("","za").isO3Country, "South Africa", 27),
        Country("kr", Locale("","kr").isO3Country, "South Korea (대한민국)", 82),
        Country("ss", Locale("","ss").isO3Country, "South Sudan (‫جنوب السودان‬‎)", 211),
        Country("es", Locale("","es").isO3Country, "Spain (España)", 34),
        Country("lk", Locale("","lk").isO3Country, "Sri Lanka (ශ්‍රී ලංකාව)", 94),
        Country("sd", Locale("","sd").isO3Country, "Sudan (‫السودان‬‎)", 249),
        Country("sr", Locale("","sr").isO3Country, "Suriname", 597),
        Country("sj", Locale("","sj").isO3Country, "Svalbard and Jan Mayen", 47),
        Country("sz", Locale("","sz").isO3Country, "Swaziland", 268),
        Country("se", Locale("","se").isO3Country, "Sweden (Sverige)", 46),
        Country("ch", Locale("","ch").isO3Country, "Switzerland (Schweiz)", 41),
        Country("sy", Locale("","sy").isO3Country, "Syria (‫سوريا‬‎)", 963),
        Country("tw", Locale("","tw").isO3Country, "Taiwan (台灣)", 886),
        Country("tj", Locale("","tj").isO3Country, "Tajikistan", 992),
        Country("tz", Locale("","tz").isO3Country, "Tanzania", 255),
        Country("th", Locale("","th").isO3Country, "Thailand (ไทย)", 66),
        Country("tl", Locale("","tl").isO3Country, "Timor-Leste", 670),
        Country("tg", Locale("","tg").isO3Country, "Togo", 228),
        Country("tk", Locale("","tk").isO3Country, "Tokelau", 690),
        Country("to", Locale("","to").isO3Country, "Tonga", 676),
        Country("tt", Locale("","tt").isO3Country, "Trinidad and Tobago", 1868),
        Country("tn", Locale("","tn").isO3Country, "Tunisia (‫تونس‬‎)", 216),
        Country("tr", Locale("","tr").isO3Country, "Turkey (Türkiye)", 90),
        Country("tm", Locale("","tm").isO3Country, "Turkmenistan", 993),
        Country("tc", Locale("","tc").isO3Country, "Turks and Caicos Islands", 1649),
        Country("tv", Locale("","tv").isO3Country, "Tuvalu", 688),
        Country("vi", Locale("","vi").isO3Country, "U.S. Virgin Islands", 1340),
        Country("ug", Locale("","ug").isO3Country, "Uganda", 256),
        Country("ua", Locale("","ua").isO3Country, "Ukraine (Україна)", 380),
        Country("ae", Locale("","ae").isO3Country, "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)", 971),
        Country("gb", Locale("","gb").isO3Country, "United Kingdom", 44),
        Country("uy", Locale("","uy").isO3Country, "Uruguay", 598),
        Country("uz", Locale("","uz").isO3Country, "Uzbekistan (Oʻzbekiston)", 998),
        Country("vu", Locale("","vu").isO3Country, "Vanuatu", 678),
        Country("va", Locale("","va").isO3Country, "Vatican City (Città del Vaticano)", 39),
        Country("ve", Locale("","ve").isO3Country, "Venezuela", 58),
        Country("vn", Locale("","vn").isO3Country, "Vietnam (Việt Nam)", 84),
        Country("wf", Locale("","wf").isO3Country, "Wallis and Futuna", 681),
        Country("eh", Locale("","eh").isO3Country, "Western Sahara (‫الصحراء الغربية‬‎)", 212),
        Country("ye", Locale("","ye").isO3Country, "Yemen (‫اليمن‬‎)", 967),
        Country("zm", Locale("","zm").isO3Country, "Zambia", 260),
        Country("zw", Locale("","zw").isO3Country, "Zimbabwe", 263),
        Country("ax", Locale("","ax").isO3Country, "Åland Islands", 358)
    )
}